#!/bin/bash
# Mind: chmod +x *.sh 

echo "We clean up the installed node modules."
rm -rf node_modules

echo "We clean up all the generated JavaScript files. Must later be regenerated by tsc."
find . -not -path "./node_modules/*" -type f -name '*.js' -delete